version: '3.9'
services:
  webserver:
    image: nginx:latest
    container_name: TwinklTestServer
    ports:
      - 80:80
    volumes:
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony_app:/var/www/html
    depends_on:
      - mysql-db
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    container_name: TwinklPhp
    env_file: .env
    depends_on:
      - mysql-db
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    expose:
      - 9003
    volumes:
      - ./symfony_app:/var/www/html:delegated
      - ./docker/config/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  mysql-db:
    image: mysql:8.0
    env_file: .env
    ports:
      - "33066:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8009:80"
    env_file: .env

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    container_name: mailhogservice
    ports:
      - 1025:1025
      - 8025:8025
